---
abstract: 'Simplistic system management'
author:
  - 'Ohio-Pennsylvania Software, LLC.'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sysync
no_index:
  directory:
    - defaults
    - inc
  file:
    - post_install.PL
requires:
  Digest::MD5: 0
  File::Copy: 0
  IPC::Open3: 0
  YAML: 0
  perl: 5.8.4
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.1
